### ISSUE TITLE
I've deployed this project using Docker, here is my Dockerfile

### ISSUE THREAD

**Issue by wangjh7** [Hugo-Persson/texify-wep-api#2]
```Dockerfile
FROM python:3.11-slim

WORKDIR /app

COPY . .

RUN python -m venv myenv && \
    . myenv/bin/activate && \
    pip install --no-cache-dir flask texify

EXPOSE 5000

CMD ["/app/myenv/bin/python", "main.py"]
```

**Comment by wangjh7** [comment]
Wonder If I could submit this file as a PR, to help others  like me who want to  deploy this using Docker, even though this file itself is not so complex?

**Comment by wangjh7** [comment]
Additionally, the last line of the `main.py` file will cause an error like below when deploying the project to a server instead of running it locally
```
FetchError: request to http://192.168.1.100:5000/predict failed, reason: connect ECONNEREFUSED 192.168.1.100:5000
```
[similar to this one](https://github.com/Hugo-Persson/obsidian-ocrlatex/issues/12)

**Comment by wangjh7** [comment]
Because Flask only listens to local requests if we code in this way
```python
if __name__ == '__main__':
    app.run(debug=True)
```
If we provide host='0.0.0.0' and a port, Flask will be able to listen for external requests
```python
if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=True)
```

**Comment by Hugo-Persson** [comment]
Thank you, @wangjh7 !

Could you create a PR and I will merge it in?

**Comment by wangjh7** [comment]
Hi, @Hugo-Persson, I've submit my PR[#3](https://github.com/Hugo-Persson/texify-wep-api/pull/3)

**Comment by Hugo-Persson** [comment]
Thank you @wangjh7 !

It is merged in 🙂
